### ISSUE TITLE
Missing access database.

### ISSUE THREAD

**Issue by joaovdev** [PacktPublishing/Data-Analysts-Toolbox-Excel-Python-Power-BI-Alteryx-Qlik-Sense-R-Tableau#2]
The access database used in "/Advanced PivotTables/Course Files/Section 2/" is just a link file.

**Comment by Sonakshis** [comment]
Apologise for the inconvenience and thank you for brining this tour attention. We have updated the GitHub repository with the correct file. Happy learning!
